<a href="https://colab.research.google.com/github/wei-wei122/114-2-ProgramingLanguage/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [3]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [4]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1PXxNLAHsfL1_WmXYe4Jz11kk_S-thY7DzZCPNWcRA30/edit?gid=0#gid=0')

In [5]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

Empty DataFrame
Columns: [日期, 時間, 分類, 品項, 金額, 付款人, 地點, 支付方式, 備註]
Index: []

In [6]:
import datetime

In [27]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

name = input("請輸入付款人: ")
place = input("請輸入地點: ")
way = input("請輸入付款方式: ")
note = input("備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-08
請輸入時間 (格式：HH:MM): 13:00
請輸入付款人: wei
請輸入地點: 7-11
請輸入付款方式: 現金
備註:

In [11]:
date_str

'2026-03-08'

In [12]:
time_str

'12:00'

In [14]:
name

'wei'

In [16]:
note

'x'

In [28]:
# 讓使用者輸入品項
item = input("請輸入品項: ")

# 讓使用者輸入金額，並確保是數字
while True:
    try:
        amount = float(input("請輸入金額: "))
        break
    except ValueError:
        print("金額必須是數字，請重新輸入。")

# 讓使用者輸入分類
category_str = input("請輸入分類: ")

# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': category_str, # 使用使用者輸入的分類
    '品項': item,
    '金額': amount,
    '付款人': name,       # 使用使用者輸入的付款人
    '地點': place,      # 使用使用者輸入的地點
    '支付方式': way,    # 使用使用者輸入的支付方式
    '備註': note        # 使用使用者輸入的備註
}])

# 使用 concat() 將新資料合併到舊的 df 中
# 檢查 df 是否為空，如果是，則直接賦值；否則進行合併
if df.empty:
    df = new_data
else:
    df = pd.concat([df, new_data], ignore_index=True)

請輸入品項: bbb
請輸入金額: 9999
請輸入分類: y

In [29]:
df

           日期     時間 分類   品項      金額  付款人    地點 支付方式 備註
0  2026-03-08  12:00  x  aaa   999.0  wei  7-11   現金  x
1  2026-03-08  13:00  y  bbb  9999.0  wei  7-11   現金

In [30]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！